load("@bazel_tools//tools/build_defs/repo:maven_rules.bzl", "maven_aar")
load("@bazel_tools//tools/build_defs/repo:maven_rules.bzl", "maven_jar")

maven_jar(
    name = "rxjava",
    artifact = "io.reactivex:rxjava:1.1.6",
    sha1 = "2586312cd2b8a511e4c6236736f5a039fc0f2273",
)

maven_aar(
    name = "rxandroid",
    artifact = "io.reactivex:rxandroid:1.2.1",
    sha1 = "78179b876174994f66432947fa15338ba13747a4",
)

android_sdk_repository(
    name = "androidsdk",
    path = "/home/user/Android/Sdk",
    api_level = 25,
    build_tools_version = "25.0.0",
)
