load("@bazel_tools//tools/build_defs/repo:maven_rules.bzl", "maven_aar")
load("@bazel_tools//tools/build_defs/repo:maven_rules.bzl", "maven_jar")

maven_jar(
    name = "rxjava",
    artifact = "io.reactivex:rxjava:1.1.6",
)

maven_aar(
    name = "rxandroid",
    artifact = "io.reactivex:rxandroid:1.2.1",
)

android_sdk_repository(
    name = "androidsdk",
    path = "/home/user/Android/Sdk",
    api_level = 25,
    build_tools_version = "25.0.0",
)
